#ifndef CONSTANTS_H
#define CONSTANTS_H

#include <SDL.h>

#define WINDOW_WIDTH 720
#define WINDOW_HEIGHT 720
#define NANOS_PER_SEC 1000000000LL  // Number of nanoseconds in a second
#define SCALE_FACTOR 4              // Scale ratio, 4=180x180px
#define WIDTH (WINDOW_WIDTH / SCALE_FACTOR)
#define HEIGHT (WINDOW_HEIGHT / SCALE_FACTOR)
#define GRID_UNIT 1

// Pulse per quarter note
#define PPQN 24
#define LINES_PER_BAR 4             // Assuming we're always in 4/4
#define PATTERN_LENGTH 16

// MAX/MIN Macro
#define MAX(a,b) ((a) > (b) ? (a) : (b))
#define MIN(a,b) ((a) < (b) ? (a) : (b))

// blipr key mapping
#define BLIPR_KEY_1 SDL_SCANCODE_1
#define BLIPR_KEY_2 SDL_SCANCODE_2
#define BLIPR_KEY_3 SDL_SCANCODE_3
#define BLIPR_KEY_4 SDL_SCANCODE_4
#define BLIPR_KEY_5 SDL_SCANCODE_Q
#define BLIPR_KEY_6 SDL_SCANCODE_W
#define BLIPR_KEY_7 SDL_SCANCODE_E
#define BLIPR_KEY_8 SDL_SCANCODE_R
#define BLIPR_KEY_9 SDL_SCANCODE_A
#define BLIPR_KEY_10 SDL_SCANCODE_S
#define BLIPR_KEY_11 SDL_SCANCODE_D
#define BLIPR_KEY_12 SDL_SCANCODE_F
#define BLIPR_KEY_13 SDL_SCANCODE_Z
#define BLIPR_KEY_14 SDL_SCANCODE_X
#define BLIPR_KEY_15 SDL_SCANCODE_C
#define BLIPR_KEY_16 SDL_SCANCODE_V

#define BLIPR_KEY_A SDL_SCANCODE_7
#define BLIPR_KEY_B SDL_SCANCODE_8
#define BLIPR_KEY_C SDL_SCANCODE_9
#define BLIPR_KEY_D SDL_SCANCODE_0

#define BLIPR_KEY_SHIFT_1 SDL_SCANCODE_LSHIFT
#define BLIPR_KEY_SHIFT_2 SDL_SCANCODE_LCTRL
#define BLIPR_KEY_SHIFT_3 SDL_SCANCODE_RSHIFT
#define BLIPR_KEY_SHIFT_4 SDL_SCANCODE_RCTRL

// blipr programs
#define BLIPR_PROGRAM_SEQUENCER 1

#endif // CONSTANTS_H